### ISSUE TITLE
Register an ESAL

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#10]
- Review if a ESAL can be registered in the backend through the endpoint ([Help here](https://www.notion.so/Registrar-ESAL-e24cad6fc5204583bb264fb751bad9c9))
- If this functionality is not implemented or it does not work properly, finish it.

**Comment by Marius9595** [comment]
In order to avoid testing another feature "Confirmation of email" this has to be executed in database : 
![image](https://user-images.githubusercontent.com/63452003/200195133-3b35e073-b4d7-4704-bedf-d7e403cb4b84.png)
![image](https://user-images.githubusercontent.com/63452003/200195366-11dff235-e082-4d6c-9e5f-3d0368922cd3.png)
![image](https://user-images.githubusercontent.com/63452003/200195453-7e3318e5-6f6a-4a63-89f5-591f67040c4d.png)
