### ISSUE TITLE
Register a volunteer

### ISSUE THREAD

**Issue by mariasoria** [lean-mind/huella-positiva#7]
- Review if a volunteer can be registered in the backend through the endpoint ([Help here](https://www.notion.so/Registrar-de-Voluntarios-c54f1d57fd2d4244ab68a9efa718f458))
- If this functionality is not implemented or it does not work properly, finish it.

**Comment by Marius9595** [comment]
This feature was implemented and works as expected through Requests (CODE 201 and Database record appears):

 
![image](https://user-images.githubusercontent.com/63452003/200192856-d04c5a82-4e22-4204-8adf-41476a8558ff.png)


![image](https://user-images.githubusercontent.com/63452003/200192923-72633ad4-b77d-48f0-a7d9-357c9f1f6591.png)

![image](https://user-images.githubusercontent.com/63452003/200193141-12a9b37b-db9b-4baa-96b9-8a8b4b6377b0.png)

**Comment by Marius9595** [comment]
However, Test declared about this feature are failing. The reason is the following:
_`java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7`_

In GitHub, I found a possible solution:
https://github.com/abashev/vfs-s3/issues/71 

I have tried to apply this, but another errors is raised...

Could someone check this to fix it and close this task?
